# src/OC/PlatformBundle/Resources/config/routing.yml

app_home:
    path:      /questionnaire/{client_id}
    defaults:  { _controller: AppBundle:Home:index}

app_datecomande:
    path:      /d/{hash}
    defaults:  { _controller: AppBundle:Home:date}

app_merci:
    path:      /merci/{client_id}
    defaults:  { _controller: AppBundle:Home:merci}

app_default:
    path:      /_merci
    defaults:  { _controller: AppBundle:Home:default}



# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /_merci
        permanent: true